version: '3'
services:
  redis-server:
    image: redis:latest
    command: --save 60 1 --loglevel warning
    container_name: redis-server
    ports:
      - 6379:6379
    networks:
      - redis-network
    volumes:
      - redis-data:/data
  backend:
    build: 
      context: ./
    container_name: redis-chat-backend
    ports:
      - 4000:4000
    networks:
      - redis-network
  frontend:
    build:
      context: ./client
    container_name: redis-chat-frontend
    ports:
      - 3000:3000
    networks:
      - redis-network
volumes:
  redis-data:
    driver: local
networks:
  redis-network:
    driver: bridge
